VivesBlog.Ui.Mvc/Models/Article.cs
using System.ComponentModel.DataAnnotations;

namespace VivesBlog.Ui.Mvc.Models
{
    public class Article
    {
        public int Id { get; set; }
        public required string Title { get; set; }
        public required string Description { get; set; }
        public required string Content { get; set; }
        public DateTime CreatedDate { get; set; }

        [Required]
        public int? AuthorId { get; set; }
        public Person? Author { get; set; }
    }
}

VivesBlog.Ui.Mvc/Models/ErrorViewModel.cs
namespace VivesBlog.Ui.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VivesBlog.Ui.Mvc/Models/Person.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VivesBlog.Ui.Mvc.Models
{
    public class Person
    {
        public int Id { get; set; }
        public required string FirstName { get; set; }
        public required string LastName { get; set; }
        [EmailAddress]
        public string? Email { get; set; }

        [ForeignKey(nameof(Article.AuthorId))]
        public IList<Article> Articles { get; set; } = new List<Article>();
    }
}

VivesBlog.Ui.Mvc/Controllers/ArticlesController.cs
using JetBrains.Annotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VivesBlog.Ui.Mvc.Core;
using VivesBlog.Ui.Mvc.Models;

namespace VivesBlog.Ui.Mvc.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly VivesBlogDbContext _dbContext;

        public ArticlesController(VivesBlogDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var articles = _dbContext.Articles
                .Include(a => a.Author)
                .ToList();
            return View(articles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return CreateEditView("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Article article)
        {
            if (!ModelState.IsValid)
            {
                return CreateEditView("Create", article);
            }

            article.CreatedDate = DateTime.UtcNow;

            _dbContext.Articles.Add(article);

            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var article = _dbContext.Articles
                .FirstOrDefault(a => a.Id == id);

            if (article is null)
            {
                return RedirectToAction("Index");
            }

            return CreateEditView("Edit", article);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([FromRoute]int id, Article article)
        {
            if (!ModelState.IsValid)
            {
                return CreateEditView("Edit", article);
            }

            var dbArticle = _dbContext.Articles.FirstOrDefault(a => a.Id == id);

            if (dbArticle is null)
            {
                return RedirectToAction("Index");
            }

            dbArticle.Title = article.Title;
            dbArticle.AuthorId = article.AuthorId;
            dbArticle.Description = article.Description;
            dbArticle.Content = article.Content;

            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        private IActionResult CreateEditView([AspMvcView] string viewName, Article? article = null)
        {
            var people = _dbContext.People
                .OrderBy(p => p.FirstName)
                .ThenBy(p => p.LastName)
                .ToList();

            ViewBag.People = people;

            return View(viewName, article);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var article = _dbContext.Articles
                .FirstOrDefault(a => a.Id == id);

            if (article is null)
            {
                return RedirectToAction("Index");
            }

            return View(article);
        }

        [HttpPost("Articles/Delete/{id:int}")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var article = new Article
            {
                Id = id,
                Title = string.Empty,
                Description = string.Empty,
                Content = string.Empty,
            };
            _dbContext.Articles.Remove(article);
            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

VivesBlog.Ui.Mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using VivesBlog.Ui.Mvc.Core;
using VivesBlog.Ui.Mvc.Models;

namespace VivesBlog.Ui.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly VivesBlogDbContext _dbContext;

        public HomeController(VivesBlogDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var articles = _dbContext.Articles
                .Include(a => a.Author)
                .ToList();
            return View(articles);
        }

        [HttpGet]
        public IActionResult Read([FromRoute]int id)
        {
            var article = _dbContext.Articles.FirstOrDefault(a => a.Id == id);

            if (article is null)
            {
                return RedirectToAction("Index");
            }

            return View(article);
        }
        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VivesBlog.Ui.Mvc/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using VivesBlog.Ui.Mvc.Core;
using VivesBlog.Ui.Mvc.Models;

namespace VivesBlog.Ui.Mvc.Controllers
{
    public class PeopleController : Controller
    {
        private readonly VivesBlogDbContext _dbContext;

        public PeopleController(VivesBlogDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var people = _dbContext.People.ToList();
            return View(people);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Person person)
        {
            if (!ModelState.IsValid)
            {
                return View(person);
            }
            
            _dbContext.People.Add(person);

            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var person = _dbContext.People
                .FirstOrDefault(a => a.Id == id);

            if (person is null)
            {
                return RedirectToAction("Index");
            }

            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([FromRoute]int id, Person person)
        {
            if (!ModelState.IsValid)
            {
                return View(person);
            }

            var dbPerson = _dbContext.People.FirstOrDefault(a => a.Id == id);

            if (dbPerson is null)
            {
                return RedirectToAction("Index");
            }

            dbPerson.FirstName = person.FirstName;
            dbPerson.LastName = person.LastName;
            dbPerson.Email = person.Email;

            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var person = _dbContext.People
                .FirstOrDefault(a => a.Id == id);

            if (person is null)
            {
                return RedirectToAction("Index");
            }

            return View(person);
        }

        [HttpPost("People/Delete/{id:int}")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var person = new Person
            {
                Id = id,
                FirstName = string.Empty,
                LastName = string.Empty
            };
            _dbContext.People.Remove(person);
            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

VivesBlog.Ui.Mvc/Views/Articles/ArticleRowPartial.cshtml
@model Article

@{
    var localDateTime = Model.CreatedDate.ToLocalTime();
}

<tr>
    <td>@Model.Title</td>
    <td>
        @if (Model.Author is not null)
        {
            @: @Model.Author.FirstName @Model.Author.LastName
        }
        else
        {
            @: No author assigned
        }
    </td>
    <td>@localDateTime.ToLongDateString() @localDateTime.ToShortTimeString()</td>
    <td>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-success">Edit</a>
        <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
    </td>
</tr>

VivesBlog.Ui.Mvc/Views/Articles/Create.cshtml
@model Article

@{
    ViewBag.Title = "Create Article";
}

<h1>@ViewBag.Title</h1>

<form method="post">
    <partial name="CreateEditPartial" model="Model" />

    <button type="submit" class="btn btn-primary">Create</button>
</form>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

VivesBlog.Ui.Mvc/Views/Articles/CreateEditPartial.cshtml
@model Article


@{
    var people = (IList<Person>)ViewBag.People;
}

<div asp-validation-summary="ModelOnly"></div>

<div class="mb-3">
    <label asp-for="Title" class="form-label"></label>
    <input asp-for="Title" class="form-control" />
    <span asp-validation-for="Title"></span>
</div>
<div class="mb-3">
    <label asp-for="Description" class="form-label"></label>
    <input asp-for="Description" class="form-control" />
    <span asp-validation-for="Description"></span>
</div>
<div class="mb-3">
    <label asp-for="AuthorId" class="form-label">Choose an author:</label>
    <select asp-for="AuthorId" class="form-control">
        <option value="">No author</option>
        @foreach (var person in people)
        {
            <option value="@person.Id">@person.FirstName @person.LastName</option>
        }
    </select>
</div>
<div class="mb-3">
    <label asp-for="Content" class="form-label"></label>
    <textarea asp-for="Content" class="form-control"></textarea>
    <span asp-validation-for="Content"></span>
</div>

VivesBlog.Ui.Mvc/Views/Articles/Delete.cshtml
@model Article

@{
    ViewBag.Title = "Create Article";
}

<h1>@ViewBag.Title</h1>

<form method="post">
    <p>Are you sure you want to delete @Model.Title?</p>
    <a asp-action="Index" class="btn btn-light">No</a>
    <button type="submit" class="btn btn-danger">Yes</button>
</form>

VivesBlog.Ui.Mvc/Views/Articles/Edit.cshtml
@model Article

@{
    ViewBag.Title = "Edit Article";
}

<h1>@ViewBag.Title</h1>

<form method="post">
    <partial name="CreateEditPartial" model="Model" />

    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts
{
    <partial name="_ValidationScriptsPartial"/>
}

VivesBlog.Ui.Mvc/Views/Articles/Index.cshtml
@model IList<Article>
@{
    ViewBag.Title = "Blog Management";
}

<h1>@ViewBag.Title</h1>

<a asp-action="Create" class="btn btn-primary">Create new Article</a>

<table class="table table-dark table-striped">
    <thead>
    <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Created</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var article in Model)
    {
        <partial name="ArticleRowPartial" model="article"/>
    }
    </tbody>
</table>

VivesBlog.Ui.Mvc/Views/Home/ArticleCardPartial.cshtml
@model Article

@{
    var localDateTime = Model.CreatedDate.ToLocalTime();
    var random = new Random();
    var colors = new List<string>
    {
        "text-white bg-primary",
        "text-white bg-secondary",
        "text-white bg-success",
        "text-white bg-danger",
        "text-dark bg-warning",
        "text-dark bg-info",
        "text-dark bg-light",
        "text-white bg-dark"
    };
    var colorIndex = random.Next(colors.Count - 1);
    var color = colors[colorIndex];
}

<div class="card @color mb-3" style="max-width: 18rem;">
    <div class="card-header">@Model.Title</div>
    <div class="card-body">
        <h5 class="card-title">
            @if (Model.Author is not null)
            {
                @: by @Model.Author.FirstName @Model.Author.LastName
            }
            else
            {
                @: No author assigned
            }
        </h5>
        <p class="card-text">@Model.Description</p>
    </div>
    <div class="card-footer">
        <a class="btn btn-primary" asp-action="Read" asp-route-id="@Model.Id">Read more ...</a>
        <small>written on @localDateTime.ToLongDateString() @localDateTime.ToShortTimeString()</small>
    </div>
</div>

VivesBlog.Ui.Mvc/Views/Home/Index.cshtml
@model IList<Article>
@{
    ViewData["Title"] = "My Fancy Blog";
}

<div class="row">
    @foreach (var article in Model)
    {
        <div class="col-3">
            <partial name="ArticleCardPartial" model="article"/>
        </div>
    }
</div>

VivesBlog.Ui.Mvc/Views/Home/Read.cshtml
@model Article;

@{
    var localDateTime = Model.CreatedDate.ToLocalTime();
}

<h1>@Model.Title</h1>
<p>@Model.Description</p>
<p>@Model.Content</p>
<small>by @Model.Author on @localDateTime.ToLongDateString() @localDateTime.ToShortTimeString()</small>

VivesBlog.Ui.Mvc/Views/People/Create.cshtml
@model Person

@{
    ViewBag.Title = "Create Person";
}

<h1>@ViewBag.Title</h1>

<form method="post">
    <partial name="CreateEditPartial" model="Model" />

    <button type="submit" class="btn btn-primary">Create</button>
</form>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

VivesBlog.Ui.Mvc/Views/People/CreateEditPartial.cshtml
@model Person

<div asp-validation-summary="ModelOnly"></div>

<div class="mb-3">
    <label asp-for="FirstName" class="form-label"></label>
    <input asp-for="FirstName" class="form-control" />
    <span asp-validation-for="FirstName"></span>
</div>
<div class="mb-3">
    <label asp-for="LastName" class="form-label"></label>
    <input asp-for="LastName" class="form-control" />
    <span asp-validation-for="LastName"></span>
</div>
<div class="mb-3">
    <label asp-for="Email" class="form-label"></label>
    <input asp-for="Email" class="form-control" />
    <span asp-validation-for="Email"></span>
</div>

VivesBlog.Ui.Mvc/Views/People/Delete.cshtml
@model Person

@{
    ViewBag.Title = "Create Person";
}

<h1>@ViewBag.Title</h1>

<form method="post">
    <p>Are you sure you want to delete @Model.FirstName @Model.LastName?</p>
    <a asp-action="Index" class="btn btn-light">No</a>
    <button type="submit" class="btn btn-danger">Yes</button>
</form>

VivesBlog.Ui.Mvc/Views/People/Edit.cshtml
@model Person

@{
    ViewBag.Title = "Edit Person";
}

<h1>@ViewBag.Title</h1>

<form method="post">
    <partial name="CreateEditPartial" model="Model" />

    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts
{
    <partial name="_ValidationScriptsPartial"/>
}

VivesBlog.Ui.Mvc/Views/People/Index.cshtml
@model IList<Person>
@{
    ViewBag.Title = "People Management";
}

<h1>@ViewBag.Title</h1>

<a asp-action="Create" class="btn btn-primary">Create new Person</a>

<table class="table table-dark table-striped">
    <thead>
    <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var person in Model)
    {
        <partial name="PersonRowPartial" model="person"/>
    }
    </tbody>
</table>

VivesBlog.Ui.Mvc/Views/People/PersonRowPartial.cshtml
@model Person

<tr>
    <td>@Model.FirstName</td>
    <td>@Model.LastName</td>
    <td>
        <a href="mailto:@Model.Email">@Model.Email</a>
    </td>
    <td>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-success">Edit</a>
        <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
    </td>
</tr>

VivesBlog.Ui.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VivesBlog.Ui.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VivesBlog.Ui.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VivesBlog.Ui.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Index">Article Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People Management</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VivesBlog.Ui.Mvc
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>